### ISSUE TITLE
present at a Frictionless call?

### ISSUE THREAD

**Issue by lwinfree** [hubmapconsortium/tableschema-to-template#20]
Hi @mccalluc This is awesome! I'm wondering if you would be willing to present this at an upcoming Frictionless community call (perhaps in March)? Or, would you be interested in doing a short write up/blog about this that would go on the Frictionless site (https://frictionlessdata.io/blog/)? I would happily help write/edit a blog. Let me know if either of those is of interest to you (you can email me at lilly.winfree@okfn.org if this is annoying to discuss in an issue). Thanks for the really cool work :-)

**Comment by mccalluc** [comment]
Thanks! Happy to do both of those. Right now, though, as I'm starting to use this on our project I'm finding some issues I'd like to tackle before making a bigger publicity push.

If you have time and could do some QA, that would be really helpful... Does it actually work in the environments and and with the schemas you have at hand? What kind of additional validations would be most useful? Are there ways the output spreadsheet could be better?

I'll email you, so you have my contact info. Thanks!

**Comment by mccalluc** [comment]
Blog post is up! https://frictionlessdata.io/blog/2021/02/04/tableschema-to-template/

closing.
