### ISSUE TITLE
Include LICENSE in source distribution

### ISSUE THREAD

**Issue by kynan** [hubmapconsortium/tableschema-to-template#28]
I'm intending to package tableschema-to-template for [conda-forge](https://conda-forge.org), however this is currently blocked as the [source distribution for 0.0.12](https://files.pythonhosted.org/packages/f5/53/212c4bde0044d4af4616d6bb6a145ab0f4d2635942e9bc0a32ec7e401659/tableschema-to-template-0.0.12.tar.gz) does not include the `LICENSE` file. Could you please tag a new release and upload a new sdist that includes `LICENSE`?

After merging #27, your packaging script should do the right thing :)

**Comment by kynan** [comment]
@mccalluc any chance of addressing this please?

**Comment by mcarans** [comment]
@bherr2 Sorry to bother you, but mccalluc seems to be unavailable. Is there someone in HuBMAP Consortium who can add a `LICENSE` file to the sdist? See also PR: https://github.com/hubmapconsortium/tableschema-to-template/pull/27

**Comment by bherr2** [comment]
@shirey @ngehlenborg who is the right person to address this/maintain this codebase? Please work with @mcarans and @kynan to get this figured out. Thanks!

**Comment by shirey** [comment]
I don't have anything to do with this code. If it is still in use maybe @john-conroy, or possibly if this is used with validation tools @sunset666, can find someone to help?  If we're no longer using it maybe the repo should be forked to someone who will maintain it and closed here.

**Comment by kynan** [comment]
@john-conroy any chance you could tag a new release and build the sdist with `python3 -m build` so it includes the `LICENSE` file?

**Comment by john-conroy** [comment]
@kynan All set. Closing.
